CREATE TABLE IF NOT EXISTS USUARIO (
  USUA_CD_USUARIO INTEGER NOT NULL,
  USUA_NM_USUARIO VARCHAR(100) NOT NULL,
  USUA_NR_LOGIN VARCHAR(50) NOT NULL,
  USUA_DS_SENHA VARCHAR(255) NOT NULL,
  USUA_DH_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_USUARIO PRIMARY KEY (USUA_CD_USUARIO),
  CONSTRAINT UK_USUARIO_NR_LOGIN UNIQUE (USUA_NR_LOGIN)
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
  CATE_CD_CATEGORIA INTEGER NOT NULL,
  CATE_CD_USUARIO INTEGER NOT NULL,
  CATE_NM_CATEGORIA VARCHAR(50) NOT NULL,
  CATE_TP_CATEGORIA VARCHAR(20) NOT NULL,
  CONSTRAINT PK_CATEGORIA PRIMARY KEY (CATE_CD_CATEGORIA),
  CONSTRAINT UK_CATEGORIA_CD_USUARIO_NM_CATEGORIA UNIQUE (CATE_CD_USUARIO, CATE_NM_CATEGORIA),
  CONSTRAINT FK_CATEGORIA_USUARIO FOREIGN KEY (CATE_CD_USUARIO) REFERENCES USUARIO (USUA_CD_USUARIO)
);

CREATE TABLE IF NOT EXISTS LANCAMENTO (
  LANC_CD_LANCAMENTO INTEGER NOT NULL,
  LANC_CD_USUARIO INTEGER NOT NULL,
  LANC_CD_CATEGORIA INTEGER NOT NULL,
  LANC_DS_DESCRICAO VARCHAR(255),
  LANC_VL_VALOR DECIMAL(10,2) NOT NULL,
  LANC_DT_LANCAMENTO DATE NOT NULL,
  LANC_DH_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_LANCAMENTO PRIMARY KEY (LANC_CD_LANCAMENTO),
  CONSTRAINT FK_LANCAMENTO_USUARIO FOREIGN KEY (LANC_CD_USUARIO) REFERENCES USUARIO (USUA_CD_USUARIO),
  CONSTRAINT FK_LANCAMENTO_CATEGORIA FOREIGN KEY (LANC_CD_CATEGORIA) REFERENCES CATEGORIA (CATE_CD_CATEGORIA)
);

CREATE INDEX IF NOT EXISTS IX_CATEGORIA_01 ON CATEGORIA (CATE_CD_USUARIO);
CREATE INDEX IF NOT EXISTS IX_LANCAMENTO_01 ON LANCAMENTO (LANC_CD_USUARIO);
CREATE INDEX IF NOT EXISTS IX_LANCAMENTO_02 ON LANCAMENTO (LANC_CD_CATEGORIA);
